import type { LucideIcon } from "lucide-react";
import {
  AlertCircle,
  ArrowLeftRight,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Building2,
  Camera,
  ChartColumn,
  CheckCircle2,
  ChevronRight,
  ClipboardList,
  Clock,
  FileText,
  Flame,
  Gift,
  Grid3x3,
  Heart,
  Image,
  LayoutGrid,
  Lightbulb,
  ListOrdered,
  LineChart,
  MessageCircle,
  MessageSquareQuote,
  MousePointerClick,
  Package,
  Palette,
  Percent,
  Quote,
  Scale,
  ShieldCheck,
  Sparkles,
  SplitSquareHorizontal,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Type,
  Users,
  Zap,
} from "lucide-react";

/** Category headers on the “Layouts and placements” step. */
export const AD_STUDIO_CATEGORY_ICON: Record<string, LucideIcon> = {
  "pain-emotion": Heart,
  "product-feature": Package,
  "social-proof": Award,
  competitive: Scale,
  "audience-targeting": Target,
  educational: BookOpen,
  "offer-cta": Gift,
  "visual-style": Palette,
  "native-text": Type,
  "metrics-benefits": BarChart3,
};

/** Per-template icons for ad format rows. */
export const AD_STUDIO_TEMPLATE_ICON: Record<string, LucideIcon> = {
  "problem-pain": AlertCircle,
  "problem-solution": ChevronRight,
  "before-after": SplitSquareHorizontal,
  "bold-claim": Flame,
  "results-numbers": TrendingUp,
  "product-ui-showcase": LayoutGrid,
  "feature-highlight": Sparkles,
  "feature-grid": Grid3x3,
  "demo-snapshot": Camera,
  "testimonial-quote": Quote,
  "case-study-snapshot": ClipboardList,
  "client-logos": Building2,
  "review-screenshot": Star,
  "comparison-us-vs-them": ArrowLeftRight,
  "alternative-replacement": MousePointerClick,
  "old-way-vs-new-way": LineChart,
  "niche-callout": Target,
  "role-based-callout": Users,
  "industry-specific-callout": Building2,
  "how-it-works": ListOrdered,
  "framework-method": Brain,
  "tips-educational": Lightbulb,
  "mistake-anti-pattern": AlertCircle,
  "offer-discount": Percent,
  "free-trial": Gift,
  "limited-time-urgency": Clock,
  "guarantee-risk-reversal": ShieldCheck,
  "visual-metaphor": Image,
  "icon-headline-minimal": Type,
  "illustration-based": Palette,
  "pattern-interrupt": Zap,
  "minimalist-text-ad": Type,
  "tweet-style": MessageSquareQuote,
  "chat-screenshot-style": MessageCircle,
  "notification-style": Bell,
  "metric-comparison": ChartColumn,
  "pain-point-highlight": Flame,
  "benefit-focused": CheckCircle2,
  "outcome-focused": Trophy,
};

export function studioCategoryIcon(categoryId: string): LucideIcon {
  return AD_STUDIO_CATEGORY_ICON[categoryId] ?? LayoutGrid;
}

export function studioTemplateIcon(templateId: string): LucideIcon {
  return AD_STUDIO_TEMPLATE_ICON[templateId] ?? FileText;
}
